# Etapa 1: Instalação e Build
FROM node:20-alpine AS builder

WORKDIR /app

# Copia arquivos de dependências
COPY package*.json ./
RUN npm install

# Copia o código do front
COPY . .

# Variável de ambiente necessária durante o build para o Next.js injetar a URL da API
ARG NEXT_PUBLIC_API_URL=http://localhost:8080
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

# Gera a versão de produção otimizada
RUN npm run build

# Etapa 2: Runner (Imagem de execução)
FROM node:20-alpine AS runner

WORKDIR /app

# Copia apenas o necessário do build para manter a imagem leve
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

# O Next.js roda por padrão na 3000
EXPOSE 3000

CMD ["npm", "start"]
