// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/alterar-senha": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Altera a senha do usuário autenticado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Autenticação"
                ],
                "summary": "Alterar senha",
                "parameters": [
                    {
                        "description": "Dados para alterar senha",
                        "name": "dados",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.AlterarSenhaRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/esqueci-senha": {
            "post": {
                "description": "Envia email para redefinição de senha",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Autenticação"
                ],
                "summary": "Esqueci minha senha",
                "parameters": [
                    {
                        "description": "Email para redefinição",
                        "name": "dados",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.EsqueciSenhaRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/redefinir-senha": {
            "post": {
                "description": "Redefine a senha usando token recebido por email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Autenticação"
                ],
                "summary": "Redefinir senha",
                "parameters": [
                    {
                        "description": "Token e nova senha",
                        "name": "dados",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.RedefinirSenhaRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/clinicas": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lista todas as clínicas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clínicas"
                ],
                "summary": "Listar clínicas",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Filtrar apenas clínicas ativas",
                        "name": "ativas",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.ClinicaResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cria uma nova clínica",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clínicas"
                ],
                "summary": "Criar clínica",
                "parameters": [
                    {
                        "description": "Dados da clínica",
                        "name": "clinica",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.ClinicaRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controllers.ClinicaResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/clinicas/agenda": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lista todos os agendamentos da clínica",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agenda"
                ],
                "summary": "Listar agendamentos",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.AgendaResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cria um novo agendamento na clínica",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agenda"
                ],
                "summary": "Criar agendamento",
                "parameters": [
                    {
                        "description": "Dados do agendamento",
                        "name": "agendamento",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.AgendaRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controllers.AgendaResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/clinicas/agenda/horarios-disponiveis": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Buscar horários disponíveis para agendamento",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agenda"
                ],
                "summary": "Horários Disponíveis",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do usuário",
                        "name": "usuario_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID do procedimento",
                        "name": "procedimento_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Data no formato YYYY-MM-DD",
                        "name": "data",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/clinicas/agenda/{id}/status": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Atualiza o status de um agendamento",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agenda"
                ],
                "summary": "Atualizar status do agendamento",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do agendamento",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Novo status",
                        "name": "status",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.AtualizarStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/clinicas/{id}/configuracoes": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna as configurações da clínica",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clínicas"
                ],
                "summary": "Buscar configurações da clínica",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da clínica",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.ConfiguracaoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Atualiza as configurações da clínica",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clínicas"
                ],
                "summary": "Atualizar configurações da clínica",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da clínica",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados da configuração",
                        "name": "configuracao",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.ConfiguracaoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.ConfiguracaoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/convenios": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cadastrar um novo convênio",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Convênios"
                ],
                "summary": "Cadastrar Convênio",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/convenios/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Atualizar um convênio existente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Convênios"
                ],
                "summary": "Atualizar Convênio",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do convênio",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/dashboard": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna métricas gerais da clínica",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Dashboard principal",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.DashboardResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/dashboard/agendamentos-hoje": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna os agendamentos do dia atual",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Agendamentos de hoje",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.AgendamentoHojeResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/dashboard/estatisticas": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna estatísticas básicas da clínica",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Estatísticas da clínica",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.EstatisticasResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/financeiro/abrir": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Abrir módulo financeiro",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Financeiro"
                ],
                "summary": "Abrir Financeiro",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Autentica um usuário e retorna um token JWT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Autenticação"
                ],
                "summary": "Login de usuário",
                "parameters": [
                    {
                        "description": "Dados de login",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/pacientes": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lista todos os pacientes da clínica",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pacientes"
                ],
                "summary": "Listar pacientes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.PacienteResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cria um novo paciente na clínica",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pacientes"
                ],
                "summary": "Criar paciente",
                "parameters": [
                    {
                        "description": "Dados do paciente",
                        "name": "paciente",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.PacienteRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controllers.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/pacientes/{cpf}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Busca um paciente específico pelo CPF",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pacientes"
                ],
                "summary": "Buscar paciente por CPF",
                "parameters": [
                    {
                        "type": "string",
                        "description": "CPF do paciente",
                        "name": "cpf",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.PacienteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/procedimentos": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lista todos os procedimentos da clínica",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Procedimentos"
                ],
                "summary": "Listar procedimentos por clínica",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Filtrar apenas procedimentos ativos",
                        "name": "ativas",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.ProcedimentoResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cadastra um novo procedimento na clínica",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Procedimentos"
                ],
                "summary": "Cadastrar procedimento",
                "parameters": [
                    {
                        "description": "Dados do procedimento",
                        "name": "procedimento",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.ProcedimentoRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controllers.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/usuarios": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lista todos os usuários da clínica",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuários"
                ],
                "summary": "Listar usuários",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Filtrar apenas usuários ativos",
                        "name": "ativos",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.UsuarioResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cria um novo usuário na clínica",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuários"
                ],
                "summary": "Criar usuário",
                "parameters": [
                    {
                        "description": "Dados do usuário",
                        "name": "usuario",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.UsuarioRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controllers.UsuarioResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/usuarios/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Busca um usuário específico pelo ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuários"
                ],
                "summary": "Buscar usuário por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do usuário",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.UsuarioResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Atualiza os dados de um usuário",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuários"
                ],
                "summary": "Atualizar usuário",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do usuário",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados do usuário",
                        "name": "usuario",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.UsuarioRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.UsuarioResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Desativa um usuário",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuários"
                ],
                "summary": "Desativar usuário",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do usuário",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/usuarios/{id}/horarios": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna os horários de trabalho do usuário",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuários"
                ],
                "summary": "Buscar horários do usuário",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do usuário",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.UsuarioHorarioResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Define os horários de trabalho do usuário",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuários"
                ],
                "summary": "Definir horários do usuário",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do usuário",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Horários do usuário",
                        "name": "horarios",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.DefinirHorariosRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.AgendaRequest": {
            "type": "object",
            "required": [
                "data_hora",
                "paciente_id",
                "procedimento_id",
                "usuario_id"
            ],
            "properties": {
                "convenio_id": {
                    "type": "integer",
                    "example": 1
                },
                "data_hora": {
                    "type": "string",
                    "example": "2024-01-15T10:00:00Z"
                },
                "observacoes": {
                    "type": "string",
                    "example": "Paciente com alergia"
                },
                "paciente_id": {
                    "type": "integer",
                    "example": 1
                },
                "procedimento_id": {
                    "type": "integer",
                    "example": 1
                },
                "usuario_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "controllers.AgendaResponse": {
            "type": "object",
            "properties": {
                "clinica_id": {
                    "type": "integer",
                    "example": 1
                },
                "convenio_id": {
                    "type": "integer",
                    "example": 1
                },
                "data_hora": {
                    "type": "string",
                    "example": "2024-01-15T10:00:00Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "observacoes": {
                    "type": "string",
                    "example": "Paciente com alergia"
                },
                "paciente_id": {
                    "type": "integer",
                    "example": 1
                },
                "procedimento_id": {
                    "type": "integer",
                    "example": 1
                },
                "status_id": {
                    "type": "integer",
                    "example": 1
                },
                "usuario_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "controllers.AgendamentoHojeResponse": {
            "type": "object",
            "properties": {
                "horario": {
                    "type": "string",
                    "example": "10:00"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "observacoes": {
                    "type": "string",
                    "example": "Paciente com alergia"
                },
                "paciente_nome": {
                    "type": "string",
                    "example": "Maria Silva"
                },
                "procedimento_nome": {
                    "type": "string",
                    "example": "Consulta Médica"
                },
                "status": {
                    "type": "string",
                    "example": "Agendado"
                },
                "usuario_nome": {
                    "type": "string",
                    "example": "Dr. João"
                }
            }
        },
        "controllers.AgendamentoResumo": {
            "type": "object",
            "properties": {
                "data_hora": {
                    "type": "string",
                    "example": "2024-01-15 10:00"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "paciente": {
                    "type": "string",
                    "example": "Maria Silva"
                },
                "procedimento": {
                    "type": "string",
                    "example": "Consulta"
                }
            }
        },
        "controllers.AlterarSenhaRequest": {
            "type": "object",
            "required": [
                "nova_senha",
                "senha"
            ],
            "properties": {
                "nova_senha": {
                    "type": "string",
                    "example": "novaSenha456"
                },
                "senha": {
                    "type": "string",
                    "example": "senhaAtual123"
                }
            }
        },
        "controllers.AtualizarStatusRequest": {
            "type": "object",
            "required": [
                "status_id"
            ],
            "properties": {
                "status_id": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "controllers.ClinicaRequest": {
            "type": "object",
            "required": [
                "cnpj",
                "email",
                "endereco",
                "nome",
                "telefone"
            ],
            "properties": {
                "cnpj": {
                    "type": "string",
                    "example": "12.345.678/0001-90"
                },
                "email": {
                    "type": "string",
                    "example": "contato@clinica.com"
                },
                "endereco": {
                    "type": "string",
                    "example": "Rua das Flores, 123"
                },
                "nome": {
                    "type": "string",
                    "example": "Clínica São João"
                },
                "telefone": {
                    "type": "string",
                    "example": "(11) 99999-9999"
                }
            }
        },
        "controllers.ClinicaResponse": {
            "type": "object",
            "properties": {
                "ativo": {
                    "type": "boolean",
                    "example": true
                },
                "cnpj": {
                    "type": "string",
                    "example": "12.345.678/0001-90"
                },
                "email": {
                    "type": "string",
                    "example": "contato@clinica.com"
                },
                "endereco": {
                    "type": "string",
                    "example": "Rua das Flores, 123"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "nome": {
                    "type": "string",
                    "example": "Clínica São João"
                },
                "telefone": {
                    "type": "string",
                    "example": "(11) 99999-9999"
                }
            }
        },
        "controllers.ConfiguracaoRequest": {
            "type": "object",
            "properties": {
                "email_notificacao": {
                    "type": "string",
                    "example": "contato@clinica.com"
                },
                "funciona_domingo": {
                    "type": "boolean",
                    "example": false
                },
                "horario_fim_domingo": {
                    "type": "string",
                    "example": ""
                },
                "horario_fim_sabado": {
                    "type": "string",
                    "example": "12:00"
                },
                "horario_fim_semana": {
                    "type": "string",
                    "example": "18:00"
                },
                "horario_inicio_domingo": {
                    "type": "string",
                    "example": ""
                },
                "horario_inicio_sabado": {
                    "type": "string",
                    "example": "08:00"
                },
                "horario_inicio_semana": {
                    "type": "string",
                    "example": "08:00"
                },
                "intervalo_consulta": {
                    "type": "integer",
                    "example": 30
                },
                "limite_agendamentos_dia": {
                    "type": "integer",
                    "example": 50
                },
                "mensagem_boas_vindas": {
                    "type": "string",
                    "example": "Bem-vindo à nossa clínica!"
                },
                "permite_agendamento_fds": {
                    "type": "boolean",
                    "example": false
                },
                "telefone_whatsapp": {
                    "type": "string",
                    "example": "11999999999"
                },
                "tempo_antecedencia": {
                    "type": "integer",
                    "example": 24
                }
            }
        },
        "controllers.ConfiguracaoResponse": {
            "type": "object",
            "properties": {
                "clinica_id": {
                    "type": "integer",
                    "example": 1
                },
                "email_notificacao": {
                    "type": "string",
                    "example": "contato@clinica.com"
                },
                "funciona_domingo": {
                    "type": "boolean",
                    "example": false
                },
                "horario_fim_domingo": {
                    "type": "string",
                    "example": ""
                },
                "horario_fim_sabado": {
                    "type": "string",
                    "example": "12:00"
                },
                "horario_fim_semana": {
                    "type": "string",
                    "example": "18:00"
                },
                "horario_inicio_domingo": {
                    "type": "string",
                    "example": ""
                },
                "horario_inicio_sabado": {
                    "type": "string",
                    "example": "08:00"
                },
                "horario_inicio_semana": {
                    "type": "string",
                    "example": "08:00"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "intervalo_consulta": {
                    "type": "integer",
                    "example": 30
                },
                "limite_agendamentos_dia": {
                    "type": "integer",
                    "example": 50
                },
                "mensagem_boas_vindas": {
                    "type": "string",
                    "example": "Bem-vindo à nossa clínica!"
                },
                "permite_agendamento_fds": {
                    "type": "boolean",
                    "example": false
                },
                "telefone_whatsapp": {
                    "type": "string",
                    "example": "11999999999"
                },
                "tempo_antecedencia": {
                    "type": "integer",
                    "example": 24
                }
            }
        },
        "controllers.DashboardResponse": {
            "type": "object",
            "properties": {
                "agendamentos_hoje": {
                    "type": "integer",
                    "example": 12
                },
                "agendamentos_semana": {
                    "type": "integer",
                    "example": 45
                },
                "pacientes_ativos": {
                    "type": "integer",
                    "example": 140
                },
                "proximos_agendamentos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.AgendamentoResumo"
                    }
                },
                "receita_mes": {
                    "type": "number",
                    "example": 15000.5
                },
                "total_pacientes": {
                    "type": "integer",
                    "example": 150
                },
                "total_procedimentos": {
                    "type": "integer",
                    "example": 25
                },
                "total_usuarios": {
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "controllers.DefinirHorariosRequest": {
            "type": "object",
            "required": [
                "horarios"
            ],
            "properties": {
                "horarios": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.UsuarioHorarioRequest"
                    }
                }
            }
        },
        "controllers.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Erro na operação"
                }
            }
        },
        "controllers.EsqueciSenhaRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "usuario@exemplo.com"
                }
            }
        },
        "controllers.EstatisticaMensal": {
            "type": "object",
            "properties": {
                "mes": {
                    "type": "string",
                    "example": "2024-01"
                },
                "total": {
                    "type": "integer",
                    "example": 25
                },
                "valor": {
                    "type": "number",
                    "example": 5000
                }
            }
        },
        "controllers.EstatisticasResponse": {
            "type": "object",
            "properties": {
                "agendamentos_por_mes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.EstatisticaMensal"
                    }
                },
                "pacientes_por_mes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.EstatisticaMensal"
                    }
                },
                "procedimentos_populares": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.ProcedimentoPopular"
                    }
                },
                "receita_por_mes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.EstatisticaMensal"
                    }
                }
            }
        },
        "controllers.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "senha"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "usuario@exemplo.com"
                },
                "senha": {
                    "type": "string",
                    "example": "123456"
                }
            }
        },
        "controllers.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "usuario": {
                    "$ref": "#/definitions/controllers.UsuarioInfo"
                }
            }
        },
        "controllers.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Operação realizada com sucesso"
                }
            }
        },
        "controllers.PacienteRequest": {
            "type": "object",
            "required": [
                "cpf",
                "email",
                "nome",
                "telefone"
            ],
            "properties": {
                "cpf": {
                    "type": "string",
                    "example": "123.456.789-00"
                },
                "data_nasc": {
                    "type": "string",
                    "example": "1990-01-01"
                },
                "email": {
                    "type": "string",
                    "example": "maria@exemplo.com"
                },
                "endereco": {
                    "type": "string",
                    "example": "Rua das Flores, 123"
                },
                "nome": {
                    "type": "string",
                    "example": "Maria Silva"
                },
                "telefone": {
                    "type": "string",
                    "example": "(11) 99999-9999"
                }
            }
        },
        "controllers.PacienteResponse": {
            "type": "object",
            "properties": {
                "ativo": {
                    "type": "boolean",
                    "example": true
                },
                "clinica_id": {
                    "type": "integer",
                    "example": 1
                },
                "cpf": {
                    "type": "string",
                    "example": "123.456.789-00"
                },
                "data_nasc": {
                    "type": "string",
                    "example": "1990-01-01"
                },
                "email": {
                    "type": "string",
                    "example": "maria@exemplo.com"
                },
                "endereco": {
                    "type": "string",
                    "example": "Rua das Flores, 123"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "nome": {
                    "type": "string",
                    "example": "Maria Silva"
                },
                "telefone": {
                    "type": "string",
                    "example": "(11) 99999-9999"
                }
            }
        },
        "controllers.ProcedimentoPopular": {
            "type": "object",
            "properties": {
                "nome": {
                    "type": "string",
                    "example": "Consulta Médica"
                },
                "total": {
                    "type": "integer",
                    "example": 45
                }
            }
        },
        "controllers.ProcedimentoRequest": {
            "type": "object",
            "required": [
                "nome",
                "valor"
            ],
            "properties": {
                "descricao": {
                    "type": "string",
                    "example": "Consulta médica geral"
                },
                "duracao": {
                    "type": "integer",
                    "example": 30
                },
                "nome": {
                    "type": "string",
                    "example": "Consulta Médica"
                },
                "valor": {
                    "type": "number",
                    "example": 150
                }
            }
        },
        "controllers.ProcedimentoResponse": {
            "type": "object",
            "properties": {
                "ativo": {
                    "type": "boolean",
                    "example": true
                },
                "clinica_id": {
                    "type": "integer",
                    "example": 1
                },
                "descricao": {
                    "type": "string",
                    "example": "Consulta médica geral"
                },
                "duracao": {
                    "type": "integer",
                    "example": 30
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "nome": {
                    "type": "string",
                    "example": "Consulta Médica"
                },
                "valor": {
                    "type": "number",
                    "example": 150
                }
            }
        },
        "controllers.RedefinirSenhaRequest": {
            "type": "object",
            "required": [
                "nova_senha",
                "token"
            ],
            "properties": {
                "nova_senha": {
                    "type": "string",
                    "example": "novaSenha123"
                },
                "token": {
                    "type": "string",
                    "example": "abc123token"
                }
            }
        },
        "controllers.UsuarioHorarioRequest": {
            "type": "object",
            "required": [
                "dia_semana",
                "horario_fim",
                "horario_inicio"
            ],
            "properties": {
                "ativo": {
                    "type": "boolean",
                    "example": true
                },
                "dia_semana": {
                    "type": "integer",
                    "maximum": 6,
                    "minimum": 0,
                    "example": 1
                },
                "horario_fim": {
                    "type": "string",
                    "example": "18:00"
                },
                "horario_inicio": {
                    "type": "string",
                    "example": "08:00"
                }
            }
        },
        "controllers.UsuarioHorarioResponse": {
            "type": "object",
            "properties": {
                "ativo": {
                    "type": "boolean",
                    "example": true
                },
                "dia_semana": {
                    "type": "integer",
                    "example": 1
                },
                "dia_semana_texto": {
                    "type": "string",
                    "example": "Segunda-feira"
                },
                "horario_fim": {
                    "type": "string",
                    "example": "18:00"
                },
                "horario_inicio": {
                    "type": "string",
                    "example": "08:00"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "usuario_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "controllers.UsuarioInfo": {
            "type": "object",
            "properties": {
                "clinica_id": {
                    "type": "integer",
                    "example": 1
                },
                "email": {
                    "type": "string",
                    "example": "joao@exemplo.com"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "nome": {
                    "type": "string",
                    "example": "João Silva"
                },
                "tipo_usuario_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "controllers.UsuarioRequest": {
            "type": "object",
            "required": [
                "email",
                "nome",
                "senha",
                "tipo_usuario_id"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "joao@exemplo.com"
                },
                "nome": {
                    "type": "string",
                    "example": "João Silva"
                },
                "senha": {
                    "type": "string",
                    "example": "123456"
                },
                "tipo_usuario_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "controllers.UsuarioResponse": {
            "type": "object",
            "properties": {
                "ativo": {
                    "type": "boolean",
                    "example": true
                },
                "clinica_id": {
                    "type": "integer",
                    "example": 1
                },
                "email": {
                    "type": "string",
                    "example": "joao@exemplo.com"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "nome": {
                    "type": "string",
                    "example": "João Silva"
                },
                "tipo_usuario_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API Clínicas",
	Description:      "API para gestão de clínicas, procedimentos e agendamentos",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
